### ISSUE TITLE
Add configuration file

### ISSUE THREAD

**Issue by roskakori** [siisurit/check_done#2]
## Goals

- [x] When check_done is run, it parses its configuration from `.check_done.yaml`
  - [x] ...or `.yml`.
- [x] If there is no configuration file, the following error message shows and the exit code is 1:
  > Cannot find check_done configuration: .check_done.yaml

Estimate: 2h 

## Example

File `.check_done.yaml`

```yaml
- board
  - url: "https://github.com/orgs/siisurit/projects/1"
  - api_key: "$GITHUB_API_KEY"
  - trackers
    - "https://github.com/siisurit/siisurit"
    - "https://github.com/siisurit/siisurit_website"
```

## Implementation notes

Use [PyYAML](https://pyyaml.org/wiki/PyYAMLDocumentation)

Add a folder `tests/data` with example YAML files to test.
